repositories:
  - type: dans
    name: dans
    base_url: "https://ssh.datastations.nl"
    query: "qdpx"
    max_pages: 2

  - type: icpsr
    name: icpsr
    base_url: "https://www.icpsr.umich.edu"
    query: "interview"
    max_pages: 2